ALTER TABLE BOOKS ADD BESTSELLER BOOLEAN DEFAULT 0;

DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE BK_ID, BK_RENT_NUMBER INT;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE ALL_RENTS CURSOR FOR SELECT BOOK_ID FROM BOOKS;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
OPEN ALL_RENTS;
WHILE (FINISHED = 0) DO
        FETCH ALL_RENTS INTO BK_ID;
        IF (FINISHED = 0) THEN

SELECT COUNT(*) FROM RENTS
WHERE BOOK_ID = BK_ID
    INTO BK_RENT_NUMBER;

IF (BK_RENT_NUMBER >2) THEN
UPDATE BOOKS SET BESTSELLER = 1
WHERE BOOK_ID = BK_ID;
END IF;
END IF;
END WHILE;

CLOSE ALL_RENTS;
END $$

DELIMITER ;

CALL UpdateBestsellers();