CREATE TABLE STATS
(
    STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULl
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS TOTAL FROM BOOKS
WHERE BESTSELLER = true;

DELIMITER $$
CREATE EVENT UPDATE_STATS
    ON SCHEDULE EVERY 1 MINUTE
    DO
        BEGIN
            DECLARE BEST_COUNT INT;
            CALL UpdateBestSellers();
            SELECT TOTAL FROM BESTSELLERS_COUNT INTO BEST_COUNT;
                INSERT INTO STATS(STAT_DATE, STAT, VALUE)
                    VALUES (CURTIME(), 'BESTSELLERS', BEST_COUNT);
        END $$
DELIMITER ;